env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
plugins: [prettier]
parserOptions:
  ecmaVersion: latest
rules: { prettier/prettier: error }
overrides:
  - env:
      mocha: true
    files:
      - '**/*.test.js'
    rules:
      no-console: 0
      no-unused-expressions: 0
